name: run-tests

on:
    push:
        branches: [master, main]
    pull_request:
        branches: [master, main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v4
            with:
                python-version: 3.11
          - run: pip install -r requirements.txt
          - run: pytest
          - uses: actions/upload-artifact@v4
            if: always()
            with:
                name: upload-logs
                path: logs/app.log
                retention-days: 30
