name: Run tests

on:
    push:
        branches: [master, main]
    pull_request:
        branches: [master, main]	
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
             - uses: actions/checkout@v2
             - uses: actions/setup-python@v2
               with:
                   python-version: 3.11
             - run: pip install -r requirements.txt
             - run: pytest